### ISSUE TITLE
Uso de la base de datos: Docentes

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#134]
Para poder utilizar los datos de _docentes_, debemos generar los controladores, rutas y vistas correspondientes. Para ello, sigue los pasos de los ejercicios de la [sección 3 ](./036_ejerciciosControladores.md) adaptándolos para los datos docentes.

Los datos que los controladores anteriores deben suministrar a las vistas, ya no estarán almacenados en _arrays_ sino que se obtendrán de la base de datos según las siguientes directrices:

1. Adapta el método `getIndex()` para que obtenga toda la lista de docentes desde la base de datos usando el modelo `Docente` y que se pase a la vista ese listado.
1. Adapta el método `getShow()` para que obtenga el docente pasado por parámetro usando el método `findOrFail()` y se pase a la vista dicho docente.
1. Adapta el método `getEdit()` para que obtenga el docente pasado por parámetro usando el método `findOrFail()` y se pase a la vista dicho docente.

> Si al probarlo te aparece el error `Class 'App\Http\Controllers\Docente' not found` revisa si has indicado el espacio de nombres del modelo que vas a utilizar (`use App\Models\Docente;`).

También deberás actualizar las vistas para que, en lugar de acceder a los datos del _array_, los obtenga del objeto con el docente utilizando `$docente->campo`.

Además, en la vista `docentes/index.blade.php`, en vez de utilizar el índice del _array_ (`$key`) como identificador para crear el enlace a `docentes/show/{id}`, tendremos que utilizar el campo `id` del docente (`$docente->id`). Lo mismo en la vista `docentes/show.blade.php`, para generar el enlace de editar docente tendremos que añadir el identificador del docente a la ruta `docentes/edit`.

**Comment by DonHonorio** [comment]
¿La migración de docentes de donde la sacamos?

**Comment by albsierra** [comment]
En el mensaje del AulaVirtual en el que os explicaba la tarea, se os decía:

> _Los issues [Uso de la base de datos: Docentes](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/134) y [Uso de la base de datos: Estudiantes](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/133) sólo se podrán asignar y realizar una vez que se hayan completado los anteriores._

Por lo tanto, hasta que no se haya realizado el issue [4.7.1. Ejercicios de Bases de Datos de Docentes](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/129) no se puede realizar este.
