### ISSUE TITLE
Calificaciones de Proyectos

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#211]
En estos momentos, suponemos que la calificación de los proyectos está en el atributo `metadatos`. No obstante, es un atributo sobre el que queremos realizar consultas, por lo que necesitamos realizar ciertos cambios.

Necesitamos que la tabla `proyectos` incorpore una columna que se llame `calificacion` y que tendrá un valor entre `1` y `10`, pudiendo ser `null`.

La calificación se le podrá poner en el momento de la creación o en la edición del proyecto.

Por último, debemos hacer que, en el momento de crear los registros para rellenar la tabla proyectos, se asigne una calificación aleatoria entre 3 y 10. _(No nos engañemos, es difícil obtener menos de un 5 en el proyecto)_

**Comment by Manuelfsr** [comment]
Aceptarlo please.
