### ISSUE TITLE
Documento de reconocimiento

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#296]
Debemos permitir que, en la creación y edición de un reconocimiento se suba una imagen que refleje dicha participación en la actividad.

El estudiante, la Actividad y el Docente, se deben elegir utilizando <select> cuyo valor sea el id correspondiente, mientras que lo que se muestre sea los nombres.

**Comment by DonHonorio** [comment]
@albsierra cuando hablas de subir una imagen que refleje la participación en la actividad, lo dices literalmente, o solo tenemos que permitir que se elija la actividad, estudiante y docente por el nombre??

**Comment by albsierra** [comment]
closed by #376
