### ISSUE TITLE
Datos del reconocimiento

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#297]
En la vista index de reconocimientos, deberían aparecer los siguientes datos:
- Nombre y apellidos del Estudiante
- Nombre de la Actividad

En la vista show de reconocimientos, deberían aparecer, además de los anteriores, los siguientes datos:
- Un enlace al documento que refleja la participación
- validación
  - Si la participación se ha validado por un docente, debe aparecer un mensaje de validado por y el nombre y apellidos del docente.
  - Si la participación no ha sido validada todavía, debe aparecer un botón de validar que asigne, al atributo validador del reconocimiento, el identificador del usuario autenticado.

**Comment by raulIzquierdoPujante** [comment]
@albsierra el nombre de la actividad no es una columna existente. En su lugar voy a  mostrar el ID de la actividad

**Comment by albsierra** [comment]
@raulIzquierdoPujante No. Tenéis que poner el nombre de la actividad, que tendréis que recoger haciendo una búsqueda en la base de datos con el id de la actividad.

**Comment by albsierra** [comment]
@raulIzquierdoPujante utilizad los siguientes nombres de actividades:
```

Premio a la excelencia en F.P.
F.P. Sin Barreras
Empresarias que marcan la diferencia
Visita a las instalaciones de Pramac
Realidad Virtual en Prevención de Riesgos Laborales
Innova y Emprende FEST
Escape Room financiero
Pruebas Libres a Ciclos Formativos
Aula de Emprendimiento
C3Runner
```

**Comment by avcluis** [comment]
-->Si la participación no ha sido validada todavía, debe aparecer un botón de validar que asigne, al atributo validador del reconocimiento, el identificador del usuario autenticado.

@albsierra 
Tengo una duda en ese apartado. Pides que si para ese reconocimiento, la columna docente_validador es null, aparezca el boton de válidar. Y cuando haga click en él asigno el id del usuario autenticado que ha hecho click .

Quizá sea una pregunta tonta, pero ante la duda prefiero preguntarte.

De primeras, lo que he hecho es: que al pulsar ese botón,  se añada el id del usuario autenticado a esa columa "docente_validador" que anteriormente era null. Pero pensándolo un poco, digo; no tiene sentido que añada el id de un usuario a la columna docente_validador. Por tanto, ¿debería crear una columna, "usuario_validador", en el caso de que el reconocimiento sea validado por un usuario y no por un docente?

**Comment by albsierra** [comment]
@avcluis De momento, ponemos el id del usuario autenticado en el atributo `docente_validador`. Más adelante nos encargaremos de asegurarnos de que ese usuario sea un docente; incluso que el docente deba ser el que está asociado a la actividad, si fuera necesario.

**Comment by ArturoGGP** [comment]
Creo que mi pullrequest esta correcto porque lo que creo que me da fallo lo tenemos los tres igual. Es posible que el fallo venga a raiz de la configuración de Breeze. Mañana lunes haré la comprobación con la máquina de clase que sí está bien configurada.

@albsierra

**Comment by ArturoGGP** [comment]
Solucionado el Error 404
