### ISSUE TITLE
Tabla reconocimientos con React-admin

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#409]
Se solicita adaptar la tabla reconocimientos para que en lugar de utilizar los `Guesser` actuales, utilice los componentes de _react-admin_ más adecuados al contenido de cada campo, siguiendo el ejemplo expuesto en [React-admin <Resource />](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/master/documentos/0613_Servidor/066_componentesRA.md).

**Comment by mrm95** [comment]
#425

**Comment by albsierra** [comment]
closed by #411
