### ISSUE TITLE
Controlador de recursos de proyectos

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#428]
Partiendo de la explicación del [controlador de recursos de ciclos](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/master/documentos/0613_Servidor/071_resourceControlerCiclos.md), extiende el proyecto actual de _Laravel_ para que sea capaz de responder a las rutas _API_ correspondientes a los recursos de tipo `proyectos`:

- `index`: Maneja una solicitud GET para recuperar todos los recursos.
- `store`: Maneja una solicitud POST para crear un nuevo recurso.
- `show`: Maneja una solicitud GET para mostrar un recurso específico.
- `update`: Maneja una solicitud PUT o PATCH para actualizar un recurso existente.
- `destroy`: Maneja una solicitud DELETE para eliminar un recurso existente.

**Comment by Manuelfsr** [comment]
#432 Mergeado el de Manuel
