### ISSUE TITLE
Cabecera X-Total-Count adaptada a filters

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#458]
La cabecera `X-Total-Count` debería indicarle al cliente el número de registros que, coinciden con las restricciones establecidas por los filtros.

En la actualidad, el servidor devuelve el número total de registros, sin tener en cuenta los filtros establecidos.

Se trata, pues, de que `X-Total-Count` indique el número de registros que se pueden obtener con los filtros establecidos.

**Comment by JavierColmena** [comment]
#483

**Comment by Manuelfsr** [comment]
#460 Mezclado el de Manuel.
