### ISSUE TITLE
Competencias-usuarios

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#488]
# Ejercicios de controladores de recursos

Se nos ha solicitado incrementar la cantidad de [tipos de recursos que debemos manejar](https://raw.githubusercontent.com/2DAW-CarlosIII/marcapersonalFP_REA/master/documentos/marcapersonalFP.drawio.png).

Entre los recursos cuyas peticiones debemos manejar, se encuentran los siguientes:

- competencias
- users-competencias

Por ello, debemos realizar todo lo necesario para que nuestra API responda a todas las peticiones posibles de los recursos asociados a las tablas anteriores.

La gestión que debemos realizar incluye:

- la definición de la tabla en la base de datos
- el llenado de las tablas con datos de prueba
- la respuesta a las rutas asociadas a los nombres de las tablas
- la definición de las páginas correspondientes en React-admin

**Comment by mxrqxxz** [comment]
Cerrado en #492
