### ISSUE TITLE
Relaciones users - ciclos

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#525]
Define las relaciones entre las tablas: 

users - ciclos

A continuación, modifica la definición del recurso correspondiente a la primera de las dos tablas para que incluya los registros relacionados de la otra tabla.

![Esquema relacional](https://raw.githubusercontent.com/2DAW-CarlosIII/marcapersonalFP_REA/master/documentos/marcapersonalFP.drawio.png)

**Comment by JavierColmena** [comment]
#544

**Comment by Manuelfsr** [comment]
#544 Mergeado el de Javier Colmena.
