### ISSUE TITLE
Relaciones users - competencias

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#526]
Define las relaciones entre las tablas: 

users - competencias

A continuación, modifica la definición del recurso correspondiente a la primera de las dos tablas para que incluya los registros relacionados de la otra tabla.

![Esquema relacional](https://raw.githubusercontent.com/2DAW-CarlosIII/marcapersonalFP_REA/master/documentos/marcapersonalFP.drawio.png)

**Comment by Manuelfsr** [comment]
#553  Mergeado el de Arturo.
