### ISSUE TITLE
Relaciones users - actividades

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#528]
Define las relaciones entre las tablas: 

users - actividades (la tabla intermedia es reconocimientos)

A continuación, modifica la definición del recurso correspondiente a la primera de las dos tablas para que incluya los registros relacionados de la otra tabla.

![Esquema relacional](https://raw.githubusercontent.com/2DAW-CarlosIII/marcapersonalFP_REA/master/documentos/marcapersonalFP.drawio.png)

**Comment by Manuelfsr** [comment]
#542 Mergeado el de Jesús.
