### ISSUE TITLE
Relaciones actividades - reconocimientos

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#530]
Define las relaciones entre las tablas: 

actividades - reconocimientos

A continuación, modifica la definición del recurso correspondiente a la primera de las dos tablas para que incluya los registros relacionados de la otra tabla.

![Esquema relacional](https://raw.githubusercontent.com/2DAW-CarlosIII/marcapersonalFP_REA/master/documentos/marcapersonalFP.drawio.png)

**Comment by Manuelfsr** [comment]
#537 Mergeado el de Jonatan, junto con Alberto.
