### ISSUE TITLE
Información del docente de los proyectos

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#569]
El cliente nos pide que, en lugar de aparecer en los recursos de Proyecto el docente_id, que también aparezca su nombre.

Tened cuidado con no generar un bucle infinito si devolvemos un recurso `user`asociado al proyecto.

**Comment by Manuelfsr** [comment]
Para evitar el bucle, devuelvo solo el nombre asociado.
