### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#667]
Se trata de que el usuario pueda modificar su avatar, subiendo una imagen a través de la vista Edit de React-admin.

Esta imagen será pública.

Para visualizar dicha imagen en el perfil, debemos enviar esa imagen a través de la propiedad `avatar` que recibe el `authProvider` en el método `getIdentity`. Por ejemplo, si hacemos la siguiente modificación en ese método del `authProvider` veremos un icono con un avatar:

```
     getIdentity: () => {
         return dataProvider.getIdentity()
             .then(( data ) => {
+                data.json.avatar = 'http://acreditacion.educadgo.gob.mx/static/img/user.png'
                 return data.json
             })
             .catch(() => {
```

**Comment by JavierColmena** [comment]
#679
