### ISSUE TITLE
fichero curriculo

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#668]
Se trata de que un estudiante pueda modificar su `pdf_curriculo`, subiendo un fichero a través de la vista Edit de React-admin.

El fichero **NO** será público.

Para su descarga, se deberá implementar un endpoint `GET /curriculos/pdf/{id}` que recoja el fichero correspondiente a ese `$id` y lo envíe como descarga. El código para la descarga podrá ser similar al siguiente:
```
    $path = storage_path().'/'.'app'.'/curriculos/'.$curriculo->pdf_curriculo;
    if (file_exists($path)) {
        return Response::download($path);
    }
```

**Comment by JavierColmena** [comment]
#681
