### ISSUE TITLE
Modificación del Proyecto para Trabajar con un Repositorio Común

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcapersonalFP23_24#694]
Partiendo del desarrollo explicado en el fichero [Consumiendo API externas](./12_apiExterna.md), vamos a modificarlo de tal manera que, en el caso de que el proyecto no tenga asignado un valor en el atributo `url_github`, el proyecto no genere un nuevo repositorio. En lugar de eso, los ficheros se deben enviar, a través del método `pushZipFiles` de `GitHubServiceProvider`, al repositorio común definido en la variable de entorno `GITHUB_PROYECTOS_REPO`. En nuestro caso, este repositorio será `https://github.com/2DAW-CarlosIII/proyectosRepo`.

Los archivos se deben enviar tantas veces como ciclos formativos asociados al proyecto haya, creando o utilizando una estructura de archivos `/ciclo/año/ficherosProyecto`.

### Detalles del Ejercicio

1. Verificar si `url_github` está presente en el proyecto.
2. Si `url_github` no está presente:
   1. Obtener la variable de entorno `GITHUB_PROYECTOS_REPO`.
   2. Para cada ciclo formativo asociado al proyecto:
      1. Crear o utilizar la estructura de archivos `/{ciclo}/{año}/ficherosProyecto`.
      2. Utilizar el método `pushZipFiles` de `GitHubServiceProvider` para enviar los archivos al repositorio común.

### Plazos

- Fecha límite **entrega**: 14 de febrero a las 23:59.
- Fecha límite **revisión**: 15 de febrero a las 23:59.

**Comment by Manuelfsr** [comment]
Mergeado el pull de Honorio #697
